# Generated by Django 4.0.1 on 2023-11-14 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=64)),
                ('field_type', models.CharField(choices=[('date', 'date'), ('phone', 'phone'), ('email', 'email'), ('text', 'text')], max_length=64)),
                ('template_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.formtemplate')),
            ],
        ),
    ]
